# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sway-git = {
    pname = "sway-git";
    version = "bf2b79b2845a070d84aafaf95e6cfcf9af7eeb9b";
    src = fetchFromGitHub {
      owner = "swaywm";
      repo = "sway";
      rev = "bf2b79b2845a070d84aafaf95e6cfcf9af7eeb9b";
      fetchSubmodules = false;
      sha256 = "sha256-qwDyl5/JrJgvRCh6HA9KuxSlhaS+90LpJ5FTtOkHGbk=";
    };
    date = "2023-12-06";
  };
  wlroots-git = {
    pname = "wlroots-git";
    version = "395a08f5d19151b6a1a6e788c9f112a00953ec37";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots.git";
      rev = "395a08f5d19151b6a1a6e788c9f112a00953ec37";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xr8ZAbMHvEDqObzlPdp8Va8q3/BPOUIZdl2Mg39jaKw=";
    };
  };
}
